zfs-automount: Enable error reporting and check script exit code.

diff --git a/plugins/zfs.automount/source/event/disks_mounted b/plugins/zfs.automount/source/event/disks_mounted
--- a/plugins/zfs.automount/source/event/disks_mounted
+++ b/plugins/zfs.automount/source/event/disks_mounted
@@ -2,3 +2,8 @@
 
 SCRIPT_DIR=$(dirname "$0")
 php "$SCRIPT_DIR/../automount.php" mount
+exit_code=$?
+if [ $exit_code -ne 0 ]; then
+    logger -t zfs.automount "[error] Automount script exited with error code $exit_code"
+    /usr/local/emhttp/webGui/scripts/notify -e "ZFS Automount" -d "Automount script exited with error code $exit_code" -i "alert"
+fi
